server:
   port: @eureka.server.port@

eureka:
   instance:
       hostname: @eureka.server.host@
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/